### ISSUE TITLE
Data-pipeline file paths locally vs in GH Actions

### ISSUE THREAD

**Issue by kmal808** [CodeWithAloha/Hawaii-Zoning-Atlas#85]
### Overview
Current notebook is hardcoded to run in GH Actions using the `data-pipeline` path. Ideally we would be able to run the notebook locally and in GH Actions with the same file path ie no changes. 

### Action Items
Derive a way to make it work either with separate file paths for locally and in Actions, or one path to rule them all.

### Resources
See https://github.com/marketplace/actions/run-notebook#parameters here for potential way of handling the two variations. 

Workflow run for reference https://github.com/CodeWithAloha/Hawaii-Zoning-Atlas/actions/runs/5185033840.

**Comment by airyclam** [comment]
## Github Action Failure Root Cause

Developers may be using IDE instead of running on Jupyter Server. There are [known issues](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000551684-Jupyter-Notebook-default-working-directory) with relative paths when running a Jupyter notebook in Jetbrains IDE

Forum post linked includes a solution for getting same behavior as running on a Jupyter server. Will submit a PR with directory relative to the notebook.
